# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodlep/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/instantnoodlep

PRODUCT_COPY_FILES += \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/General_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Global_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Handset_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Headset_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Speaker_cal.acdb \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/ashdr/ncf_pack.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack.ncf \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/ashdr/ncf_pack_imx471.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_imx471.ncf \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/ashdr/ncf_pack_imx586.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_imx586.ncf \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/ashdr/ncf_pack_imx689.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_imx689.ncf \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/ashdr/ncf_pack_s5k3m5.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_s5k3m5.ncf \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/calibrationOutput_IR.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/calibrationOutput_IR.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/calibrationOutput_uw.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/calibrationOutput_uw.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/calibrationOutput_wt.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/calibrationOutput_wt.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/darksight/darksight_main.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/darksight/darksight_main.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/darksight/darksight_ultrawide.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/darksight/darksight_ultrawide.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/camera/distortion_result.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/distortion_result.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/init/calibrationOutput_IR.rc:$(TARGET_COPY_OUT_ODM)/etc/init/calibrationOutput_IR.rc \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/init/calibrationOutput_uw.rc:$(TARGET_COPY_OUT_ODM)/etc/init/calibrationOutput_uw.rc \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/init/calibrationOutput_wt.rc:$(TARGET_COPY_OUT_ODM)/etc/init/calibrationOutput_wt.rc \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_T0_tcs3408.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_T0_tcs3408.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_ak991x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_ak991x_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_bmi26x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_bmi26x_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_cct.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_cct.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_cct_rear.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_icm4x6xx.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_icm4x6xx.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_lsm6dsm_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_lsm6dsm_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_lsm6dso.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_lsm6dso.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_mmc5603x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_mmc5603x_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_stk2232_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_stk2232_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_sx9324_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_sx9324_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_sx9324up_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_sx9324up_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_sx933x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_sx933x_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_tcs3408.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_tcs3408.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_qrd_tcs3707.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_tcs3707.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/sensor/config/kona_stk3a6x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_stk3a6x_0.json \
    vendor/oneplus/instantnoodlep/proprietary/odm/etc/wifi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/bdwlan.elf \
    vendor/oneplus/instantnoodlep/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.semco_imx586.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.semco_imx586.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.semco_imx586_BG.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.semco_imx586_BG.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.semco_imx689.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.semco_imx689.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.semco_imx689_MP.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.semco_imx689_MP.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.semco_s5k3m5.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.semco_s5k3m5.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.shine_gc5035.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.shine_gc5035.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.sensormodule.truly_imx471.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.truly_imx471.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.tuned.semco_imx586.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.semco_imx586.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.tuned.semco_imx586_BG.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.semco_imx586_BG.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.tuned.semco_imx689.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.semco_imx689.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.tuned.semco_s5k3m5.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.semco_s5k3m5.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.tuned.shine_gc5035.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.shine_gc5035.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti.tuned.truly_imx471.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.truly_imx471.bin \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti_instantnoodlep.sensor.gc5035.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodlep.sensor.gc5035.so \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti_instantnoodlep.sensor.imx471.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodlep.sensor.imx471.so \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti_instantnoodlep.sensor.imx586.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodlep.sensor.imx586.so \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti_instantnoodlep.sensor.imx689.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodlep.sensor.imx689.so \
    vendor/oneplus/instantnoodlep/proprietary/odm/lib64/camera/com.qti_instantnoodlep.sensor.s5k3m5.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodlep.sensor.s5k3m5.so \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b00 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b01 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b02 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b03 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b04 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b05 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b06 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b07 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9608.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.mdt \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b00 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b01 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b02 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b03 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b04 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b05 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b06 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b07 \
    vendor/oneplus/instantnoodlep/proprietary/odm/vendor/firmware/gfp9638.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.mdt \
    vendor/oneplus/instantnoodlep/proprietary/vendor/bin/hw/android.hardware.keymaster@4.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@4.0-service-qti \
    vendor/oneplus/instantnoodlep/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/oneplus/instantnoodlep/proprietary/vendor/lib64/libkeymasterdeviceutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterdeviceutils.so \
    vendor/oneplus/instantnoodlep/proprietary/vendor/lib64/libkeymasterprovision.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterprovision.so \
    vendor/oneplus/instantnoodlep/proprietary/vendor/lib64/libkeymasterutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterutils.so \
    vendor/oneplus/instantnoodlep/proprietary/vendor/lib64/libqtikeymaster4.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqtikeymaster4.so
